🍋PBL課題_POSTメソッドを使った機能とAjaxを使った機能を作成
Itsuki1031/test pull request #7
Opened 2023-10-16 15:34 UTC by Itsuki1031

2023-10-16 15:38 UTC, taikis requested changes
もしコメントした点に自分なりの理由があれば個々に返信して欲しい

2023-10-16 15:38 UTC, taikis commented on templates/login.html
>  			</form>
Getでいいのかな？

2023-10-16 15:38 UTC, taikis commented on templates/index1.html
> +    </form>
example_formはあっていいの？

2023-10-16 15:48 UTC, Itsuki1031 commented on templates/login.html
>  			</form>
ログインの機能を実装するためにはGETでは良くないですが、現時点ではログイン機能を実装していないためとりあえず次のページに行ければ良いという考えでGETにしています。

2023-10-16 16:07 UTC, Itsuki1031 commented on templates/index1.html
> +    </form>
この部分はAjaxの機能を使用して場所などの情報を入力したいという意図で作成しました。Ajaxの機能は実装できましたがformがずっと残ったままなど理想の動作はしなかったのでDBの実装と合わせて改良したいと考えていました。

2023-10-17 00:22 UTC, taikis approved these changes
ちゃんと考えてたのでOKにします

2023-10-17 16:01 UTC, merged